algorithm: LongDiffThroughOpt
config_dicts:
  hyperparameter:
    class: Adam
    lr: 0.05
  hyperparameter_wrapper:
    class: ExactHypergradientOptimiser
optimised_hyperparameters: [lr, weight_decay, momentum]
reset_loop_before_hyperparameter_step: 200
patch_optimiser: True

# Assuming this is being done on Fashion-MNIST
network_weight_steps: 200
hyperparameter_steps: 50
