algorithm: Ours_LR_Momentum
config_dicts:
  hyperparameter:
    class: Adam
    lr: 0.05
  hyperparameter_wrapper:
    class: NeumannHypergradientOptimiser
    hyperparameter_rollback_distance: 5
optimised_hyperparameters: [lr, weight_decay, momentum]
patch_optimiser: True
